import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: "#f9fafb", paddingTop: 50, paddingHorizontal: 16 },
    centered: { flex: 1, justifyContent: "center", alignItems: "center" },
    loadingText: { marginTop: 12, color: "#6b7280" },
    header: { marginBottom: 12 },
    backButton: { color: "#2563eb", fontSize: 15, marginBottom: 8 },
    headerTitle: { fontSize: 22, fontWeight: "bold", color: "#111827" },
    searchRow: {
        flexDirection: "row", alignItems: "center",
        backgroundColor: "#fff", borderRadius: 10,
        borderWidth: 1, borderColor: "#e5e7eb",
        paddingHorizontal: 14, marginBottom: 12, height: 46,
    },
    searchInput: { flex: 1, fontSize: 15, color: "#111827" },
    searchSpinner: { marginLeft: 8 },
    addButton: { backgroundColor: "#2563eb", padding: 14, borderRadius: 8, marginBottom: 16 },
    addButtonText: { color: "#fff", textAlign: "center", fontWeight: "bold", fontSize: 15 },
    formCard: { backgroundColor: "#fff", borderRadius: 10, padding: 16, marginBottom: 24, elevation: 2 },
    formTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 16, color: "#111827" },
    sectionDivider: {
        fontSize: 14, fontWeight: "600", color: "#2563eb",
        marginTop: 8, marginBottom: 8,
        borderTopWidth: 1, borderTopColor: "#e5e7eb", paddingTop: 16,
    },
    fieldGroup: { marginBottom: 14 },
    label: { fontSize: 13, color: "#374151", marginBottom: 6, fontWeight: "600" },
    input: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 8, padding: 12, fontSize: 15, backgroundColor: "#fff", color: "#111827" },
    textArea: { height: 70, textAlignVertical: "top" },
    dropdownButton: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 8, padding: 12, backgroundColor: "#fff" },
    dropdownText: { fontSize: 15, color: "#111827" },
    dropdownPlaceholder: { fontSize: 15, color: "#9ca3af" },
    modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "center", padding: 24 },
    modalContent: { backgroundColor: "#fff", borderRadius: 12, padding: 16, maxHeight: "70%" },
    modalTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 12, color: "#111827" },
    modalOption: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#f3f4f6" },
    modalOptionText: { fontSize: 15, color: "#374151" },
    submitButton: { backgroundColor: "#16a34a", padding: 16, borderRadius: 8, marginTop: 10, alignItems: "center" },
    submitButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    listTitle: { fontSize: 16, fontWeight: "bold", color: "#374151", marginBottom: 12 },
    emptyText: { color: "#9ca3af", textAlign: "center", marginTop: 20 },
    employeeCard: { backgroundColor: "#fff", borderRadius: 10, padding: 14, marginBottom: 10, elevation: 1 },
    employeeCardHeader: { flexDirection: "row", alignItems: "flex-start", marginBottom: 4 },
    employeeName: { fontSize: 16, fontWeight: "bold", color: "#111827" },
    employeeCode: { fontSize: 13, color: "#6b7280", fontWeight: "600", marginTop: 2 },
    employeeDetail: { fontSize: 13, color: "#6b7280", marginTop: 2 },
    inactiveBadge: {
        marginTop: 6, alignSelf: "flex-start",
        backgroundColor: "#fee2e2", color: "#dc2626",
        fontSize: 11, fontWeight: "600",
        paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4,
    },
    editButton: {
        backgroundColor: "#ffffff", borderWidth: 1, borderColor: "#ffffff",
        borderRadius: 6, paddingHorizontal: 10, paddingVertical: 5, marginLeft: 8,
    },
    editButtonText: { color: "#2563eb", fontSize: 13, fontWeight: "600" },
    editModalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
    editModalSheet: {
        backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20,
        padding: 20, maxHeight: "90%",
    },
    editModalHeader: {
        flexDirection: "row", justifyContent: "space-between",
        alignItems: "flex-start", marginBottom: 16,
    },
    editModalTitle: { fontSize: 18, fontWeight: "bold", color: "#111827" },
    editModalSubtitle: { fontSize: 13, color: "#6b7280", marginTop: 2 },
    closeBtn: { padding: 4 },
    closeBtnText: { fontSize: 18, color: "#6b7280" },
    lockedBanner: { backgroundColor: "#fef9c3", borderRadius: 8, padding: 10, marginBottom: 16 },
    lockedBannerText: { fontSize: 12, color: "#92400e" },
    toggleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
    toggleButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20 },
    toggleOn: { backgroundColor: "#16a34a" },
    toggleOff: { backgroundColor: "#9ca3af" },
    toggleText: { color: "#fff", fontWeight: "600", fontSize: 13 },
    passwordContainer: {
        flexDirection: "row", alignItems: "center",
        borderWidth: 1, borderColor: "#d1d5db",
        borderRadius: 8, backgroundColor: "#fff", paddingHorizontal: 12,
    },
    passwordInput: { flex: 1, fontSize: 15, paddingVertical: 12, color: "#111827" },
    cardActions: { flexDirection: "row", alignItems: "center", gap: 8 },
    attendanceBtn: {
        paddingHorizontal: 12, paddingVertical: 6,
        borderRadius: 6, minWidth: 72,
        alignItems: "center", justifyContent: "center",
    },
    signInBtn: { backgroundColor: "#16a34a" },
    signOutBtn: { backgroundColor: "#f97316" },
    attendanceBtnText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    presentBadge: { backgroundColor: "#dcfce7", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
    presentBadgeText: { color: "#16a34a", fontSize: 12, fontWeight: "700" },
});